# Generated by Django 2.0.7 on 2018-08-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposicao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome',
            new_name='name',
        ),
    ]
